In [1]:
from __future__ import print_function

import warnings

warnings.filterwarnings('ignore')

import argparse
import torch
import torch.utils.data
from torch.utils.data import DataLoader, TensorDataset
from torch import nn, optim
from torch.nn import functional as F

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from fooling_lime.utils import *
from fooling_lime.get_data import *

In [2]:
# Set up experiment parameters
params = Params("fooling_lime/model_configurations/experiment_params.json")
X, y, cols = get_and_preprocess_german(params)

features = [c for c in X]

gender_indc = features.index('Gender')
loan_rate_indc = features.index('LoanRateAsPercentOfIncome')

X = X.values

xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.1)
ss = StandardScaler().fit(xtrain)

In [36]:
scaler = StandardScaler().fit(X[:,:7].reshape(-1,7))
tmp = scaler.transform(X[:,:7].reshape(-1,7))
tmp[0,:7]

array([ 0.67028006, -0.19601428,  0.90819465,  2.76645648, -1.23647786,
       -0.74513141,  0.91847717])

In [35]:
inv = scaler.inverse_transform(tmp)
print(inv[0])
print(X[0,:7])

[1.000e+00 0.000e+00 1.000e+00 6.700e+01 6.000e+00 1.169e+03 4.000e+00]
[   1    0    1   67    6 1169    4]
